<a href="https://colab.research.google.com/github/RICHAR-SL/pandas/blob/main/PandaS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#IMPORTAR PANDAS
import pandas as pd
import numpy as np

In [3]:
#ayuda de pandas

help(pd.Series.iloc)

Help on property:

    Purely integer-location based indexing for selection by position.

    .. deprecated:: 2.2.0

       Returning a tuple from a callable is deprecated.

    ``.iloc[]`` is primarily integer position based (from ``0`` to
    ``length-1`` of the axis), but may also be used with a boolean
    array.

    Allowed inputs are:

    - An integer, e.g. ``5``.
    - A list or array of integers, e.g. ``[4, 3, 0]``.
    - A slice object with ints, e.g. ``1:7``.
    - A boolean array.
    - A ``callable`` function with one argument (the calling Series or
      DataFrame) and that returns valid output for indexing (one of the above).
      This is useful in method chains, when you don't have a reference to the
      calling object, but would like to base your selection on
      some value.
    - A tuple of row and column indexes. The tuple elements consist of one of the
      above inputs, e.g. ``(0, 1)``.

    ``.iloc`` will raise ``IndexError`` if a requested indexer is
    out-of-bounds, except *slice* indexers which allow out-of-bounds
    indexing (this conforms with python/numpy *slice* semantics).

    See more at :ref:`Selection by Position <indexing.integer>`.

    See Also
    --------
    DataFrame.iat : Fast integer location scalar accessor.
    DataFrame.loc : Purely label-location based indexer for selection by label.
    Series.iloc : Purely integer-location based indexing for
                   selection by position.

    Examples
    --------
    >>> mydict = [{'a': 1, 'b': 2, 'c': 3, 'd': 4},
    ...           {'a': 100, 'b': 200, 'c': 300, 'd': 400},
    ...           {'a': 1000, 'b': 2000, 'c': 3000, 'd': 4000}]
    >>> df = pd.DataFrame(mydict)
    >>> df
          a     b     c     d
    0     1     2     3     4
    1   100   200   300   400
    2  1000  2000  3000  4000

    **Indexing just the rows**

    With a scalar integer.

    >>> type(df.iloc[0])
    <class 'pandas.core.series.Series'>
    >>> df.iloc[0]
    a    1
    b    2
    c    3
    d    4
    Name: 0, dtype: int64

    With a list of integers.

    >>> df.iloc[[0]]
       a  b  c  d
    0  1  2  3  4
    >>> type(df.iloc[[0]])
    <class 'pandas.core.frame.DataFrame'>

    >>> df.iloc[[0, 1]]
         a    b    c    d
    0    1    2    3    4
    1  100  200  300  400

    With a `slice` object.

    >>> df.iloc[:3]
          a     b     c     d
    0     1     2     3     4
    1   100   200   300   400
    2  1000  2000  3000  4000

    With a boolean mask the same length as the index.

    >>> df.iloc[[True, False, True]]
          a     b     c     d
    0     1     2     3     4
    2  1000  2000  3000  4000

    With a callable, useful in method chains. The `x` passed
    to the ``lambda`` is the DataFrame being sliced. This selects
    the rows whose index label even.

    >>> df.iloc[lambda x: x.index % 2 == 0]
          a     b     c     d
    0     1     2     3     4
    2  1000  2000  3000  4000

    **Indexing both axes**

    You can mix the indexer types for the index and columns. Use ``:`` to
    select the entire axis.

    With scalar integers.

    >>> df.iloc[0, 1]
    2

    With lists of integers.

    >>> df.iloc[[0, 2], [1, 3]]
          b     d
    0     2     4
    2  2000  4000

    With `slice` objects.

    >>> df.iloc[1:3, 0:3]
          a     b     c
    1   100   200   300
    2  1000  2000  3000

    With a boolean array whose length matches the columns.

    >>> df.iloc[:, [True, False, True, False]]
          a     c
    0     1     3
    1   100   300
    2  1000  3000

    With a callable function that expects the Series or DataFrame.

    >>> df.iloc[:, lambda df: [0, 2]]
          a     c
    0     1     3
    1   100   300
    2  1000  3000

***TOMA DE CONTACTOS***:----ùù∫

In [12]:
diccionario= [{'a':1,'b':5,'c':9},{'a':3,'b':5,'c':7}]
DF=pd.DataFrame(diccionario)
DF

NameError: name 'np' is not defined

In [27]:
#crear una seria
serie=pd.Series([2,3,5,6,4],index=['a','b','c','d','e'])
serie

a    2
b    3
c    5
d    6
e    4
dtype: int64

In [ ]:
#Borra seie o fila

In [29]:
serie=pd.Series.drop(['a','b'])
serie

TypeError: super(type, obj): obj must be an instance or subtype of type

In [32]:
#Seleccionar filas o series
serie1=serie[['b','d']]
serie1

b    100
d      6
dtype: int64

In [31]:
#Asignacion
serie['b']=100
serie

a      2
b    100
c      5
d      6
e      4
dtype: int64

In [34]:
#operadore
serie4=(serie+serie1)
serie4

a      NaN
b    200.0
c      NaN
d     12.0
e      NaN
dtype: float64

In [36]:
#multiplicacion
serie_mul=serie.mul(serie4,serie)
serie_mul

a        NaN
b    20000.0
c        NaN
d       72.0
e        NaN
dtype: float64

In [37]:
#division

serie_div=serie.div(serie4,serie)
serie_div

a    NaN
b    0.5
c    NaN
d    0.5
e    NaN
dtype: float64

In [43]:
#resta
serie_res=serie.subtract(serie4,serie1)
serie_res

a      NaN
b   -100.0
c      NaN
d     -6.0
e      NaN
dtype: float64

DATAFRAME

In [62]:
datos = {'Alumno':['Marcos','Juan','Lusia','Eva'],'Nota':[20,10,15,20]}
df=pd.DataFrame(datos,columns=['Alumno','Nota'])
df

   Alumno  Nota
0  Marcos    20
1    Juan    10
2   Lusia    15
3     Eva    20

Entrada,Salida lectura y escritura

In [74]:
csvaa= df.to_csv('/content/misDatos.csv',index=False,columns=['Alumno','Nota'])
print(csvaa)

AttributeError: module 'pandas' has no attribute 'to_csv'

In [75]:
#leer dataframe
mis_datos= pd.read_csv('/content/misDatos.csv',header=None,nrows=2)
mis_datos.columns=['Alumno','Nota']
mis_datos.head()

   Alumno  Nota
0  Alumno  Nota
1  Marcos    20

In [76]:
df=pd.read_excel('/content/misDatos.xlsx')
df

  Alumno  Nota
0  M Mar     8
1  Lucia     9
2   Jose     6
3    Eva    10